import turtle
from time import sleep
obj = turtle.Turtle()

def draw_hammer(angle, pos, size):
	#obj = turtle.Turtle()
	obj.color('black', 'brown')
	obj.penup()
	obj.setpos(pos)
	obj.pendown()
	side = size//4
	obj.begin_fill()
	obj.left(angle)
	obj.forward(size)
	obj.left(90)
	obj.forward(side)
	obj.right(90)
	obj.forward(side)
	obj.right(90)
	obj.forward(side*3)
	obj.right(90)
	obj.forward(side)
	obj.right(90)
	obj.forward(side)
	obj.left(90)
	obj.forward(size)
	obj.right(90)
	obj.forward(side)
	obj.end_fill()
	obj.right(90)
	obj.right(angle)

def eye(pos, size, pupil, puppos):
	#obj = turtle.Turtle()
	obj.color('black', 'white')
	#obj.pencolor('black')
	obj.penup()
	obj.goto(pos)
	obj.pendown()
	obj.begin_fill()
	obj.circle(size)
	obj.end_fill()
	#obj_pup = turtle.Turtle()
	obj.penup()
	obj.goto(puppos)
	obj.pendown()
	obj.color('black', 'black')
	obj.begin_fill()
	obj.circle(pupil)
	obj.end_fill()
	
def mouth_tongue(pos, size, tsize):
	#obj = turtle.Turtle()
	obj.penup()
	obj.goto(pos)
	obj.pendown()
	obj.forward(size)
	tpos = (pos[0]+(size-tsize)//2, pos[1])
	obj.penup()
	obj.goto(tpos)
	obj.pendown()
	obj.color('black', 'red')
	obj.begin_fill()
	for _ in range(3):
		obj.forward(tsize)
		obj.right(120)
	obj.end_fill()
	
#draw_hammer(90, (-200, -200), 100)
#eye((-200, 500), 20, 4, (-200, 510))
#mouth_tongue((0,0), 100, 50)

def draw_face(inc):
	#obj = turtle.Turtle()
	obj.penup()
	obj.goto(0, 0)
	obj.pendown()
	obj.color('black', 'yellow')
	obj.begin_fill()
	obj.circle(100)
	obj.end_fill()
	eye((-60, 80), 30, 7, (-60+inc, 105-inc))
	eye((60, 80), 30, 7, (60-inc, 105-inc))
	mouth_tongue((-30, 30), 60, 2+(3*inc))



screen = turtle.Screen()
screen.tracer(0)
for i in range(1, 21):
	obj.clear()
	draw_face(0)
	draw_hammer(90+i*4.5, (100, 220), 100)
	screen.update()
#sleep(.5)
for i in range(15):
	obj.clear()
	draw_face(i)
	draw_hammer(180, (100, 220), 100)
	screen.update()
	#sleep(.07)
#draw_face()
sleep(2)